apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: wordpress-nfs-pv