apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_NAME
          value:  wordpress
        - name: WORDPRESS_DB_HOST
          value:  10.17.96.3:3306
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password-secret
              key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        volumeMounts:
        - name: wordpress-nfs
          mountPath: /var/www/html
      volumes:
      - name: wordpress-nfs
        persistentVolumeClaim:
          claimName: wordpress-nfs